name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - .github/PULL_REQUEST_TEMPLATE.md
      - .github/ISSUE_TEMPLATE/custom.md
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md
      - .github/PULL_REQUEST_TEMPLATE.md
      - .github/ISSUE_TEMPLATE/custom.md

  workflow_dispatch:

env:
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache Swift Package
        uses: actions/cache@v2
        with:
          path: SourcePackages
          key: ${{ runner.os }}-spm-${{ hashFiles('*.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
          restore-keys: ${{ runner.os }}-spm-

      - name: Xcode version
        run: xcodebuild -version

      - name: Install Mint
        run: brew install mint

      - name: Mint Bootstrap
        run: mint bootstrap

      - name: Generate Xcode project with XcodeGen
        run: mint run xcodegen xcodegen generate

      - name: Build
        run: xcodebuild build
          -scheme GithubClient
          -sdk iphonesimulator
          -configuration Debug
          -clonedSourcePackagesDirPath SourcePackages
          -destination "platform=iOS Simulator,name=IPhone 12"

      - name: Run Unit Test
        run: xcodebuild test
          -scheme GithubClient
          -sdk iphonesimulator
          -configuration Debug
          -clonedSourcePackagesDirPath SourcePackages
          -destination "platform=iOS Simulator,name=IPhone 12" | xcpretty
